# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.box_version = "202510.26.0"

  config.vm.provider :virtualbox do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision "shell" do |script|
    script.path = "bash_scripts/install_ansible.sh"
  end

  config.vm.provision "shell" do |script|
    script.path = "bash_scripts/install_git.sh"
  end
end