name: 'Create Yandex Cloud Infrastructure using Terraform'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.5

    - name: Write Service Account key file
      run: |
        echo '${{ secrets.YC_SA_JSON_KEY }}' > key.json
        echo '${{ secrets.YC_USER_DATA }}' > user-data.yaml

    - name: Terraform Init
      run: terraform init

    # - name: Terraform Format
    #   run: terraform fmt -check

    - name: Terraform Plan
      run: |
        terraform plan \
          -var "cloud_id=${{ secrets.YC_CLOUD_ID }}" \
          -var "folder_id=${{ secrets.YC_FOLDER_ID }}" \
          -var "service_account_key_file=key.json" \
          -var "zone=ru-central1-a"

    - name: Terraform Apply
      run: |
        terraform apply \
            -var "cloud_id=${{ secrets.YC_CLOUD_ID }}" \
            -var "folder_id=${{ secrets.YC_FOLDER_ID }}" \
            -var "service_account_key_file=key.json" \
            -var "zone=ru-central1-a"